version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
