version: "3.9"

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
      
  server:
    build: .
    command:  "npx prisma migrate dev && npm run dev"
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    depends_on:
      - db